### ISSUE TITLE
php 7.1.7 throws lots of 500-errors

### ISSUE THREAD

**Issue by halloalexkern** [kiswa/TaskBoard#380]
Running on plesk 17.5.3 with PHP 7.1.7 fpm served by apache.

PHP 7.0 and 5.6 work jst fine.

e.g.

angular.js:9866 GET http://kernboard.alexkern.com/taskboard/api/boards 500 (Internal Server Error)
(anonymous) @ angular.js:9866
sendReq @ angular.js:9667
serverRequest @ angular.js:9383
processQueue @ angular.js:13248
(anonymous) @ angular.js:13264
$eval @ angular.js:14466
$digest @ angular.js:14282
$apply @ angular.js:14571
done @ angular.js:9698
completeRequest @ angular.js:9888
requestLoaded @ angular.js:9829

angular.js:9866 GET http://kernboard.alexkern.com/taskboard/api/users/current 500 (Internal Server Error)
(anonymous) @ angular.js:9866
sendReq @ angular.js:9667
serverRequest @ angular.js:9383
processQueue @ angular.js:13248
(anonymous) @ angular.js:13264
$eval @ angular.js:14466
$digest @ angular.js:14282
$apply @ angular.js:14571
done @ angular.js:9698
completeRequest @ angular.js:9888
requestLoaded @ angular.js:9829

angular.js:9866 GET http://kernboard.alexkern.com/taskboard/api/authenticate 500 (Internal Server Error)
(anonymous) @ angular.js:9866
sendReq @ angular.js:9667
serverRequest @ angular.js:9383
processQueue @ angular.js:13248
(anonymous) @ angular.js:13264
$eval @ angular.js:14466
$digest @ angular.js:14282
$apply @ angular.js:14571
done @ angular.js:9698
completeRequest @ angular.js:9888
requestLoaded @ angular.js:9829

angular.js:11655 TypeError: fn is not a function
    at angular.js:9415
    at processQueue (angular.js:13248)
    at angular.js:13264
    at Scope.$eval (angular.js:14466)
    at Scope.$digest (angular.js:14282)
    at Scope.$apply (angular.js:14571)
    at done (angular.js:9698)
    at completeRequest (angular.js:9888)
    at XMLHttpRequest.requestLoaded (angular.js:9829)

:-) AK

**Comment by kiswa** [comment]
I won't be updating v0.3.1 to support latest PHP.

That said, v1.0.0 (`re-write` branch) supports all currently supported versions of PHP. Currently it is tested on latest 5.6, 7.0, and 7.1 at every push to GitHub.

**Comment by FiSHYsolutions** [comment]
current version (v0.3.1) doesn't work with PHP v7.2 (cgi/fpm), but PHP v7.1 seems to be fine.
